/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_appsync_graphqlEndpoint": "https://4rpyh64txfegxdwzwwbw6kyjtu.appsync-api.eu-west-3.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-3",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vkyqa6n2n5cp7ipam2krgxpfa4",
    "aws_cognito_identity_pool_id": "eu-west-3:6233ed39-7b38-4eb8-be32-f30d1ba3a74a",
    "aws_cognito_region": "eu-west-3",
    "aws_user_pools_id": "eu-west-3_91LkbbqJx",
    "aws_user_pools_web_client_id": "17435tidj9ffkrklesgv0jfe3j",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
